module.exports = {
  assemblyAIApiKey: process.env.ASSEMBLYAI_API_KEY,
  mongoURI: process.env.MONGO_URI || 'mongodb://localhost:27017/whispercart',
  openaiApiKey: process.env.OPENAI_API_KEY,
  deepgramApiKey: process.env.DEEPGRAM_API_KEY,
  huggingfaceToken: process.env.HUGGINGFACE_API_TOKEN,
  rainforestApiKey: process.env.RAINFOREST_API_KEY,
  amazonAccessKey: process.env.AMAZON_ACCESS_KEY,
  amazonSecretKey: process.env.AMAZON_SECRET_KEY,
  amazonPartnerTag: process.env.AMAZON_PARTNER_TAG,
  amazonMarketplace: process.env.AMAZON_MARKETPLACE,
  flipkartApiKey: process.env.FLIPKART_API_KEY,
  flipkartAffiliateId: process.env.FLIPKART_AFFILIATE_ID,
  meeshoApiKey: process.env.MEESHO_API_KEY,
  meeshoAffiliateId: process.env.MEESHO_AFFILIATE_ID,
  jwtSecret: process.env.JWT_SECRET,
  jwtExpire: process.env.JWT_EXPIRE,
};